In [1]:
from numpy import exp, array, random, dot

In [2]:
training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = array([[0, 1, 1, 0]]).T

In [4]:
training_set_inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [5]:
training_set_outputs

array([[0],
       [1],
       [1],
       [0]])

In [6]:
random.seed(1)
synaptic_weights = 2 * random.random((3, 1)) - 1

In [7]:
synaptic_weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [16]:
for iteration in range(20):
    output = 1 / (1 + exp(-(dot(training_set_inputs, synaptic_weights))))
    #print(output)
    synaptic_weights += dot(training_set_inputs.T, (training_set_outputs - output) * output * (1 - output))
    #print(synaptic_weights)
    #print("------------")
print (1 / (1 + exp(-(dot(array([1, 0, 0]), synaptic_weights)))))

[0.97285484]


### 本节课没有作业，自己总结和理解就可以